export { createPool, getPool, closePool, pingDatabase } from './client.js';

export {
  userRepository,
  conversationRepository,
  messageRepository,
  attachmentRepository,
  documentRepository,
  chunkRepository,
  embeddingRepository,
  sourceRepository,
  toolExecutionRepository,
  approvalRepository,
  preferenceRepository,
  memoryRepository,
  appCapabilityConfigRepository,
  appSyncRunRepository,
} from './repositories/index.js';
export type {
  User,
  UserAuthRecord,
  UserRepository,
  Conversation,
  ConversationRepository,
  Message,
  MessageRepository,
  Attachment,
  AttachmentRepository,
  Document,
  DocumentRepository,
  Chunk,
  ChunkRepository,
  Embedding,
  EmbeddingRepository,
  EmbeddingSearchFilters,
  AppSourceStats,
  IndexedSourceSummary,
  Source,
  SourceRepository,
  ToolExecution,
  ToolExecutionRepository,
  Approval,
  ApprovalRepository,
  Preference,
  PreferenceRepository,
  Memory,
  MemoryRepository,
  AppCapabilityConfig,
  AppCapabilityConfigRepository,
  AppSyncRun,
  AppSyncRunRepository,
} from './repositories/index.js';
